#!/usr/bin/env zsh

typeset -A local nav=(
  [d]="$DOTS"
  [s]="$REPOS/uni/Y1S2"
  [z]="$DOTS/zsh/.config/zsh"
)

for k dir in ${(kv)nav}; do
  [ ! -d $dir ] && echo "zsh nav: $dir doesn't exist" && continue
  alias 2$k="cd $dir"
done
unset nav k v
